/* tslint:disable */
/* eslint-disable */
/**
 * MyApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WeatherAnalysisDto,
  WeatherForecastDto,
} from '../models/index';
import {
    WeatherAnalysisDtoFromJSON,
    WeatherAnalysisDtoToJSON,
    WeatherForecastDtoFromJSON,
    WeatherForecastDtoToJSON,
} from '../models/index';

export interface AnalyzeWeatherRequest {
    weatherForecastDto: Array<WeatherForecastDto>;
}

/**
 * 
 */
export class MyApiApi extends runtime.BaseAPI {

    /**
     */
    async analyzeWeatherRaw(requestParameters: AnalyzeWeatherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['weatherForecastDto'] == null) {
            throw new runtime.RequiredError(
                'weatherForecastDto',
                'Required parameter "weatherForecastDto" was null or undefined when calling analyzeWeather().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/weatherforecast/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['weatherForecastDto']!.map(WeatherForecastDtoToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async analyzeWeather(requestParameters: AnalyzeWeatherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.analyzeWeatherRaw(requestParameters, initOverrides);
    }

    /**
     * Get latest weather analysis
     */
    async getLatestWeatherAnalysisRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeatherAnalysisDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/weatheranalysis/latest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeatherAnalysisDtoFromJSON(jsonValue));
    }

    /**
     * Get latest weather analysis
     */
    async getLatestWeatherAnalysis(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeatherAnalysisDto> {
        const response = await this.getLatestWeatherAnalysisRaw(initOverrides);
        return await response.value();
    }

}
