/* tslint:disable */
/* eslint-disable */
/**
 * MyApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WeatherForecastDto,
} from '../models/index';
import {
    WeatherForecastDtoFromJSON,
    WeatherForecastDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class WeatherHandlersApi extends runtime.BaseAPI {

    /**
     * Get weather forecast data for the next 5 days.
     * Get weather forecast
     */
    async getWeatherForecastRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecastDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/weatherforecast`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastDtoFromJSON));
    }

    /**
     * Get weather forecast data for the next 5 days.
     * Get weather forecast
     */
    async getWeatherForecast(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecastDto>> {
        const response = await this.getWeatherForecastRaw(initOverrides);
        return await response.value();
    }

}
