/* tslint:disable */
/* eslint-disable */
/**
 * MyApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherForecastDto
 */
export interface WeatherForecastDto {
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastDto
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastDto
     */
    temperatureC: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastDto
     */
    temperatureF: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastDto
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastDto
     */
    icon?: string | null;
}

/**
 * Check if a given object implements the WeatherForecastDto interface.
 */
export function instanceOfWeatherForecastDto(value: object): value is WeatherForecastDto {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('temperatureC' in value) || value['temperatureC'] === undefined) return false;
    if (!('temperatureF' in value) || value['temperatureF'] === undefined) return false;
    return true;
}

export function WeatherForecastDtoFromJSON(json: any): WeatherForecastDto {
    return WeatherForecastDtoFromJSONTyped(json, false);
}

export function WeatherForecastDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherForecastDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'temperatureC': json['temperatureC'],
        'temperatureF': json['temperatureF'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'icon': json['icon'] == null ? undefined : json['icon'],
    };
}

export function WeatherForecastDtoToJSON(json: any): WeatherForecastDto {
    return WeatherForecastDtoToJSONTyped(json, false);
}

export function WeatherForecastDtoToJSONTyped(value?: WeatherForecastDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'temperatureC': value['temperatureC'],
        'temperatureF': value['temperatureF'],
        'summary': value['summary'],
        'icon': value['icon'],
    };
}

