/* tslint:disable */
/* eslint-disable */
/**
 * MyApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherAnalysisDto
 */
export interface WeatherAnalysisDto {
    /**
     * 
     * @type {string}
     * @memberof WeatherAnalysisDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof WeatherAnalysisDto
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof WeatherAnalysisDto
     */
    analysis: string;
}

/**
 * Check if a given object implements the WeatherAnalysisDto interface.
 */
export function instanceOfWeatherAnalysisDto(value: object): value is WeatherAnalysisDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('analysis' in value) || value['analysis'] === undefined) return false;
    return true;
}

export function WeatherAnalysisDtoFromJSON(json: any): WeatherAnalysisDto {
    return WeatherAnalysisDtoFromJSONTyped(json, false);
}

export function WeatherAnalysisDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherAnalysisDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'analysis': json['analysis'],
    };
}

export function WeatherAnalysisDtoToJSON(json: any): WeatherAnalysisDto {
    return WeatherAnalysisDtoToJSONTyped(json, false);
}

export function WeatherAnalysisDtoToJSONTyped(value?: WeatherAnalysisDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'analysis': value['analysis'],
    };
}

